<?php

namespace Modules\Expenses\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\Exceptions\HttpResponseException;
use Symfony\Component\HttpFoundation\Response;

class ExpenseRequest extends FormRequest
{
    /**
     * Get the validation rules that apply to the request.
     */
    public function rules(): array
    {
        return [
            'title' => 'required|min:3|max:100',
            'amount' => 'required|numeric|min:1',
            'category' => 'required|min:3|max:100',
            'expense_date' => 'required|date|date_format:d-m-Y',
//            'notes' => ''
        ];
    }

    public function messages(): array {
        return [
            'title.required' => 'Title is required',
            'title.min' => 'Title must be at least 3 characters',
            'title.max' => 'Title may not be greater than 100 characters',
            'amount.required' => 'Amount is required',
            'amount.numeric' => 'Amount must be a number',
            'amount.min' => 'Amount must be at least 1',
            'category.required' => 'Category is required',
            'category.min' => 'Category must be at least 3 characters',
            'category.max' => 'Category may not be greater than 100 characters',
            'expense_date.required' => 'Expense date is required',
            'expense_date.date' => 'Expense date must be a date',
            'expense_date.date_format' => 'Expense date format is invalid',
        ];
    }

    public function failedValidation(Validator $validator)
    {
//        parent::failedValidation($validator); // TODO: Change the autogenerated stub
        $errors = $validator->errors();
        throw new HttpResponseException(response()->json([
            'status' => 'error',
            'errors' => $errors->toArray(),
        ], Response::HTTP_UNPROCESSABLE_ENTITY));
    }

//    /**
//     * Determine if the user is authorized to make this request.
//     */
//    public function authorize(): bool
//    {
//        return true;
//    }
}
